### ISSUE TITLE
i cannot load "application/x-wacomtabletplugin"

### ISSUE THREAD

**Issue by Luka0612** [tanatana/wacom-api-sample#1]
how can i load it

**Comment by tanatana** [comment]
Hi, @Luka0612 

To answer your question, I need more information. e.g. OS, Web Browser, your wacom tablet type etc. 

But first of all, I have to tell you that wacom's plugin is deprecated.

To be precise, the Netscape Plugin Application Programming Interface (NPAPI), used by wacom's plugin, is already retire.

I strongly recommended that use Pointer Event API instead of wacom's NPAPI plugin. It is works on Chrome, Opera, IE, Edge. (https://caniuse.com/#feat=pointer)

**Comment by Luka0612** [comment]
You are right that wacom's plugin is deprecated.I solve it, used by the latest SDK(http://developer.wacom.com/en-cn/will-sdk-digital-ink).
Thank you!
